[[asciidoc-report-plugin]]
== Asciidoc Report

The plugin records the results of executed rules (i.e. concepts and constraints).
At the end of the analysis phase http://www.asciidoctor[Asciidoctor] is used for rendering the input documents providing the rules to HTML documents. The rules blocks are identified and replaced by their status and results appended.
Furthermore include directives are provided for embedding a summary about executed and imported rules.

By default all rule files with the name `index.adoc` will be selected for rendering.
The report property `asciidoc.report.file.include` may be used to explicitly select files.
Files may be located in the rule directory of a project (e.g. `jqassistant/`) or provided by plugins.

=== jQA Include Directives

The report may be enhanced by `jQA` include directives:

`jQA:Summary[concepts="...",importedConcepts="...",constraints="...",importedConstraints="..."]`::
Includes two summary tables containing executed rules, their description, status and severity.
The filter attributes are optional, if none is given all results are included.
  `concepts` and `constraints` refer to rules that are defined in the rendered Asciidoc document(s).
  `importedConcepts` and `importedConstraints` refer to rules that are imported from plugins.
`jQA:Rules[concepts="...",constraints="..."]`::
  Embeds imported rules and their results identified by the specified filters. Both filter attributes are optional but at least one must be specified.
`jQA:ImportedRules[]`::
  `Deprecated` Renders descriptions for all imported rules which have been executed but which are not part of the document itself (i.e. provided by plugins).

TIP: Filter attributes are comma separated lists of id patterns and may contain wildcards, e.g. "layer:*, spring-\*:*".

.jqassistant/index.adoc
....
= My Project

This document describes architectural and design rules for My Project.

== Summary

\include::jQA:Summary[]

[[default]]
[role=group,includesGroups="..."]
== Project Specific Concepts & Constraints

...
project specific rules
...

== Common Spring Concepts & Constraints

\include::jQA:Rules[concepts="spring*:*",constraints="spring*:*"]
....

=== Configuration

The Asciidoc Report plugin accepts several options that might be passed as report properties to jQAssistant:

[options="header"]
|===
| Property                            | Description                                                                                                        | Default
| asciidoc.report.directory           | Specifies the directory where the HTML files will be written                                                       | jqassistant/report/asciidoc
| asciidoc.report.file.include        | A comma separated list of filter of Asciidoc files to be included (optional)                                       |
| asciidoc.report.file.exclude        | A comma separated list of filter of Asciidoc files to be excluded (optional)                                       |
|===

=== Distributing Of Asciidoc Files In Plugins

Asciidoc files may be distributed as part of plugins to allow sharing rules and reports between projects.

* Files must be located as classpath resources in the folder `/META-INF/jqassistant-rules` or sub-folders of it:
+
[source]
----
META-INF/
  |-jqassistant-plugin.xml
  |-jqassistant-rules/
    |-my-reports/
      |-index.adoc             // the document to be rendered
      |-included-rules.adoc    // a file included by index.adoc providing additional rules
      |-included-misc.adoc     // a file included by index.adoc without additional rules
----
+
TIP: Plugins should provide their reports in sub-folders (e.g. `/META-INF/jqassistant-rules/my-reports`) to avoid interferences with other plugins.
* Asciidoc files may be included using relative paths:
+
[source,asciidoc]
----
\include::included-rules.adoc[]
\include::included-misc.adoc[]
----
* File containing rules must be registered in the plugin descriptor (note that `included-misc.adoc` is not registered)
+
[source,xml]
.META-INF/jqassistant-plugin.xml
----
<jqassistant-plugin>
    <rules>
        <resource>my-reports/index.adoc</resource>
        <resource>my-reports/included-rules.adoc</resource>
    </rules>
</jqassistant-plugin>
----
* The Asciidoc files may embed PlantUML diagrams:
+
[source,asciidoc]
....
= Component Diagram

[plantuml]
.Building Block Diagram
----
@startuml
component "Component 1" as c1
component "Component 2" as c2

c1 --> c2 : Depends On
@enduml
----
....
NOTE: Embedding images or other resources into plugins that can be referenced by Asciidoc files is currently not supported.

== PlantUML Report

The plugin provides support for generating the following diagrams from rule results:

* <<ComponentDiagrams>>
* <<ClassDiagrams>>
* <<SequenceDiagrams>>

NOTE: This feature is based on http://plantuml.com/[PlantUML] which itself relies on http://www.graphviz.org[Graphviz].
The latter needs to be installed and the `dot` executable must be present on the system path.

[[ComponentDiagrams]]
=== Component Diagrams

To activate component diagram rendering the report type must be set to `plantuml-component-diagram`.
The result of the rule simply needs to return all required nodes and their relationships:

.jqassistant/index.adoc
....
[[DependencyDiagram]]
[source,cypher,role=concept,requiresConcepts="dependency:Package",reportType="plantuml-component-diagram"] // (1)
.Creates a diagram about dependencies between packages containing Java types (test artifacts are excluded).
----
MATCH
  (artifact:Main:Artifact)-[:CONTAINS]->(package:Package)-[:CONTAINS]->(:Type)
OPTIONAL MATCH
  (package)-[dependsOn:DEPENDS_ON]->(:Package)
RETURN
  package, dependsOn                                                                                           // (2)
----
....
(1) The report type is set to `plantuml-component-diagram`.
(2) The packages are returned as nodes and their dependencies (dependsOn) as relationships.

The result might also specify graph-alike structures which will be rendered as PlantUML folders.
The following example therefore uses a modified return clause:

.jqassistant/index.adoc
....
[[DependencyPerArtifactDiagram]]
[source,cypher,role=concept,requiresConcepts="dependency:Package",reportType="plantuml-component-diagram"]
.Creates a diagram about dependencies between packages containing Java types (per artifact, test artifacts are excluded).
----
MATCH
  (artifact:Main:Artifact)-[:CONTAINS]->(package:Package)-[:CONTAINS]->(:Type)
OPTIONAL MATCH
  (package)-[dependsOn:DEPENDS_ON]->(:Package)
RETURN
  {                                   // (1)
    role : "graph",                   // (2)
    parent : artifact,                // (3)
    nodes : collect(package),         // (4)
    relationships: collect(dependsOn) // (5)
  }
----
....
<1> Instead of nodes and relations a map-like structure is returned
<2> `role` determines that the map shall be interpreted as graph containing nodes and relationships
<3> `parent` specifies the node that shall be rendered as folder, i.e. the container of nodes
<4> `nodes` are the nodes to be included in the folder
<5> `relationships` are the relationships between the nodes, they may reference nodes of other parents/folders

[[ClassDiagrams]]
=== Class Diagrams

To activate class diagram rendering the report type must be set to `plantuml-class-diagram`.
The result may contain any of the following elements:

* Packages (`:Java:Package`)
* Types (`:Java:Type`)
* Members (`:Java:Member`, `:Java:Field`, `:Java:Method`)
* Inheritance relations between types (`:EXTENDS`, `:IMPLEMENTS`)
* any other type relations (rendered as associations)

.jqassistant/index.adoc
....
[[ClassDiagram]]
[source,cypher,role=concept,requiresConcepts="java:InnerType",reportType="plantuml-class-diagram"]
.Creates a class diagram.
----
MATCH
  (p:Package)-[:CONTAINS]->(t:Type)-[:DECLARES]->(m:Member) // <1>
WHERE NOT
  t:Inner
OPTIONAL MATCH
  (t)-[e:EXTENDS|IMPLEMENTS]->(:Type)                       // <2>
OPTIONAL MATCH
  (t)-[d:DEPENDS_ON]->(:Type)                               // <3>
RETURN
  *
----
....
<1> Matches Java packages, types and their declared members
<2> Optionally include super classes and implemented interfaces
<3> Optionally include any dependencies, rendered as associations

[[SequenceDiagrams]]
=== Sequence Diagrams

To activate sequence diagram rendering the report type must be set to `plantuml-sequence-diagram`.
The result of the rule must return a column `sequence` containing a path-structure:

.jqassistant/index.adoc
....
[[SequenceDiagram]]
[source,cypher,role=concept,reportType="plantuml-sequence-diagram"]
.Creates a sequence diagram.
----
MATCH
  (type:Type{name:"MyService"})-[:DECLARES]->(root:Method{signature:"void doSomething()"}),
  sequence=(root)-[:INVOKES*]->(:Method)
RETURN
  sequence // <1>
----
....
<1> The sequence to convert to a diagram

NOTE: The sequence diagram is sensitive to the order of participants and messages.
The diagram rendering algorithm therefore relies on a depth-first result structure as provided by the `path` function.
All elements are rendered in the order of their first occurrence.

If a path cannot be returned directly the result may provide the columns `participants` (nodes) and `messages` (relationships):

.jqassistant/index.adoc
....
[[SequenceDiagram]]
[source,cypher,role=concept,reportType="plantuml-sequence-diagram"]
.Creates a sequence diagram.
----
MATCH
  (type:Type{name:"MyService"})-[:DECLARES]->(root:Method{signature:"void doSomething()"}),
  sequence=(root)-[:INVOKES*]->(:Method)
RETURN
  nodes(sequence) as participants      // <1>
  relationships(sequence) as messages  // <2>
----
....
<1> The list of participants
<2> The list of messages exchanged between the participants

=== Configuration

The PlantUML Report plugin accepts several options that might be passed as report properties to jQAssistant:

[options="header"]
|===
| Property                   | Description                                                                                                        | Default
| plantuml.report.format     | Specifies the output file format of the generated PlantUML-Diagrams (optional)                                     | SVG
| plantuml.report.rendermode | Specifies the renderer used for the generated PlantUML-Diagrams, currently supporting GraphViz and Jdot (optional) | GRAPHVIZ
|===

